name: Pull Request to Master

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests-and-quality-gate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Instalação do Node.Js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Instalação de dependências
        run: yarn install

      - name: Test
        run: yarn test

      - name: Quality Gate Scan
        run: SONAR_KEY=${{ secrets.SONARQUBE_TOKEN }} SONAR_URL=${{ secrets.SONARQUBE_HOST }} make sonar-scanner
